### ISSUE TITLE
Build is broken due to external dependency hell

### ISSUE THREAD

**Issue by dmcnamara-eng** [GavinJoyce/ember-headlessui#160] opened 2022-07-12 15:22 UTC
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

ember-headlessui
└─┬ release-it
  └─┬ @octokit/rest
    └─┬ @octokit/plugin-paginate-rest
      └── ✕ unmet peer @octokit/core@>=4: found 3.6.0 in @octokit/rest
```

**Comment by NullVoxPopuli** [comment] 2022-07-12 15:26
yeah, octokit needs to fix that -- nothing we can really do here

**Comment by NullVoxPopuli** [comment] 2022-07-12 15:35
> We cannot release new version of ember-headlessui until that is fixed.

correct.
  - `@octokit/rest` - https://github.com/octokit/rest.js/blob/master/package.json#L36
    - specified `@octokit/core` v4 on the line above
    - latest https://github.com/octokit/plugin-paginate-rest.js/blob/master/package.json#L31 has correct peer.
    
So why do we have 3.6.0?     
    
 ```
 ❯ pnpm -r  why @octokit/core 
ember-headlessui@0.12.3 /home/nullvoxpopuli/Development/NullVoxPopuli/ember-headlessui/ember-headlessui

devDependencies:
release-it 14.14.3
└─┬ @octokit/rest 18.12.0
  ├── @octokit/core 3.6.0
  ├─┬ @octokit/plugin-paginate-rest 2.21.1
  │ └── @octokit/core 3.6.0 peer
  ├─┬ @octokit/plugin-request-log 1.0.4
  │ └── @octokit/core 3.6.0 peer
  └─┬ @octokit/plugin-rest-endpoint-methods 5.13.0
    └── @octokit/core 3.6.0 peer
release-it-lerna-changelog 3.1.0
└─┬ release-it 14.14.3 peer
  └─┬ @octokit/rest 18.12.0
    ├── @octokit/core 3.6.0
    ├─┬ @octokit/plugin-paginate-rest 2.21.1
    │ └── @octokit/core 3.6.0 peer
    ├─┬ @octokit/plugin-request-log 1.0.4
    │ └── @octokit/core 3.6.0 peer
    └─┬ @octokit/plugin-rest-endpoint-methods 5.13.0
      └── @octokit/core 3.6.0 peer
```

latest release-it is 15.1.1, we are not using that -- so maybe the problem is release-it. Let's upgrade that

**Comment by NullVoxPopuli** [comment] 2022-07-12 15:37
I upgraded release-it, but release-it-lerna-changelog has not been updated
```
ember-headlessui
├─┬ release-it
│ └─┬ @octokit/rest
│   └─┬ @octokit/plugin-paginate-rest
│     └── ✕ unmet peer @octokit/core@>=4: found 3.6.0 in @octokit/rest
└─┬ release-it-lerna-changelog
  └── ✕ unmet peer release-it@^14.0.0: found 15.1.1

```

**Comment by NullVoxPopuli** [comment] 2022-07-12 15:37
There is already an issue: https://github.com/rwjblue/release-it-lerna-changelog/issues/203

But rwjblue is on vacation, I think

**Comment by NullVoxPopuli** [comment] 2022-07-12 15:44
ah ok, so release-it is using @octokit/rest v18, instead of v19

**Comment by NullVoxPopuli** [comment] 2022-07-12 15:47
This should resolve : https://github.com/GavinJoyce/ember-headlessui/pull/161

**Comment by dmcnamara-eng** [comment] 2022-07-12 15:53
Nice one! I went down that road but wasn't sure on our "policy" on using forks.

**Comment by NullVoxPopuli** [comment] 2022-07-12 16:07
it's a dev-time tool, so it's not going to affect our users :see_no_evil:

**Comment by NullVoxPopuli** [comment] 2022-07-15 23:31
resolved by: https://github.com/GavinJoyce/ember-headlessui/pull/163

**Closed by NullVoxPopuli** 2022-07-15 23:31 UTC
